# This Makefile is generated by the made script:
# https://github.com/alx741/made
#
# Dependencies:
# 	tddlight (https://github.com/alx741/tdd_traffic-light)

TASK_RUNNER=stack
BUILD_COMMAND=$(TASK_RUNNER) build
TEST_COMMAND=$(TASK_RUNNER) test

export TDDLIGHT_COMPORT=/dev/ttyUSB0

.PHONY: test build

test:
	tddlight y
	$(TEST_COMMAND) && tddlight g || tddlight r

build:
	tddlight y
	$(BUILD_COMMAND) && tddlight g || tddlight r

clean:
	tddlight c
